### ISSUE TITLE
Causes IntelliJ to completely crash during startup

### ISSUE THREAD

**Issue by dininski** [opwvhk/avro-schema-support#10] opened 2021-04-16 09:42 UTC
IntelliJ version: 2020.3
OS: Linux Mint 18.3 (based on Ubuntu 16.04)

Error: 
```
Error:
021-04-16 10:32:04,088 [  16946]  ERROR - nSystem.impl.ActionManagerImpl - JDK: 11.0.4; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2021-04-16 10:32:04,088 [  16946]  ERROR - nSystem.impl.ActionManagerImpl - OS: Linux 
2021-04-16 10:32:04,089 [  16947]  ERROR - nSystem.impl.ActionManagerImpl - Plugin to blame: Apache Avro IDL Schema Support version: 203.0.0 
2021-04-16 10:32:04,089 [  16947]  ERROR - nSystem.impl.ActionManagerImpl - Last Action:  
2021-04-16 10:32:04,114 [  16972]  ERROR - nSystem.impl.ActionManagerImpl -  [Plugin: net.sf.opk.avro-schema-support] 
com.intellij.diagnostic.PluginException:  [Plugin: net.sf.opk.avro-schema-support]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.instantiate(ActionManagerImpl.java:251)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:221)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:570)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActions(ActionManagerImpl.java:1621)
	at com.intellij.openapi.actionSystem.impl.ActionPreloader.preload(ActionPreloader.java:15)
	at com.intellij.openapi.application.Preloader.lambda$preload$0(Preloader.java:84)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.application.Preloader.lambda$preload$1(Preloader.java:74)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.instantiate(ActionManagerImpl.java:241)
	... 23 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class opwvhk.intellij.avro_idl.AvroIdlFileType
	at opwvhk.intellij.avro_idl.actions.AvroIdlToSchemaAction.<init>(AvroIdlToSchemaAction.java:29)
	... 28 more
2021-04-16 10:32:04,116 [  16974]  ERROR - nSystem.impl.ActionManagerImpl - IntelliJ IDEA 2020.3.2  Build #IU-203.7148.57 
2021-04-16 10:32:04,116 [  16974]  ERROR - nSystem.impl.ActionManagerImpl - JDK: 11.0.4; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2021-04-16 10:32:04,116 [  16974]  ERROR - nSystem.impl.ActionManagerImpl - OS: Linux 
2021-04-16 10:32:04,116 [  16974]  ERROR - nSystem.impl.ActionManagerImpl - Plugin to blame: Apache Avro IDL Schema Support version: 203.0.0 
```

**Comment by GoodBoy962** [comment] 2021-05-16 20:40
the same for me on mac os

**Comment by opwvhk** [comment] 2021-05-17 09:16
Just uninstalled the plugin, restarted IntelliJ, installed the plugin again and opened an avdl file.
This didn't yield any errors.

My IntelliJ and JDK version from the log:
```
2021-05-17 10:41:00,354 [     51]   INFO -        #com.intellij.idea.Main - IDE: IntelliJ IDEA (build #IU-211.7142.45, 30 Apr 2021 12:12) 
2021-05-17 10:41:00,355 [     52]   INFO -        #com.intellij.idea.Main - OS: Mac OS X (11.3.1, x86_64) 
2021-05-17 10:41:00,366 [     63]   INFO -        #com.intellij.idea.Main - JRE: 11.0.10+9-b1341.41 (JetBrains s.r.o.) 
2021-05-17 10:41:00,366 [     63]   INFO -        #com.intellij.idea.Main - JVM: 11.0.10+9-b1341.41 (Dynamic Code Evolution 64-Bit Server VM) 
```

Same result when rechecking using IntelliJ 2020.3:
```
2021-05-17 11:04:43,697 [    102]   INFO -        #com.intellij.idea.Main - IDE: IntelliJ IDEA (build #IC-203.5981.155, 30 Nov 2020 23:31) 
2021-05-17 11:04:43,697 [    102]   INFO -        #com.intellij.idea.Main - OS: Mac OS X (10.16, x86_64) 
2021-05-17 11:04:43,705 [    110]   INFO -        #com.intellij.idea.Main - JRE: 11.0.9+11-b1145.21 (JetBrains s.r.o.) 
2021-05-17 11:04:43,706 [    111]   INFO -        #com.intellij.idea.Main - JVM: 11.0.9+11-b1145.21 (OpenJDK 64-Bit Server VM) 
```

The exception is for a missing class, which I cannot explain because it does exist: https://github.com/opwvhk/avro-schema-support/blob/master/src/main/java/opwvhk/intellij/avro_idl/AvroIdlFileType.java

Does the combination "uninstall, restart, install" change the outcome?

**Comment by opwvhk** [comment] 2021-05-17 09:22
On a side note, the exception says "Could not initialize class opwvhk.intellij.avro_idl.AvroIdlFileType".
Now the class exists, but maybe there's an exception in initializing static fields.

If the problem persists, I'd like to see the exception relating to that failure. I'll need it in order to diagnose the problem.

**Comment by raghu-megh** [comment] 2021-05-21 20:41
I see the following error and stacktrace:

com.intellij.ide.plugins.StartupAbortedException: Fatal error initializing 'com.intellij.psi.stubs.StubUpdatingIndex'
	at com.intellij.serviceContainer.ComponentManagerImplKt.handleComponentError(ComponentManagerImpl.kt:1078)
	at com.intellij.util.indexing.FileBasedIndexDataInitialization.lambda$initAssociatedDataForExtensions$0(FileBasedIndexDataInitialization.java:88)
	at com.intellij.util.indexing.IndexDataInitializer.executeTask(IndexDataInitializer.kt:75)
	at com.intellij.util.indexing.IndexDataInitializer.access$executeTask(IndexDataInitializer.kt:15)
	at com.intellij.util.indexing.IndexDataInitializer$runParallelTasks$$inlined$map$lambda$1.run(IndexDataInitializer.kt:49)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ExceptionInInitializerError
	at opwvhk.intellij.avro_idl.AvroIdlFileType.<init>(AvroIdlFileType.java:19)
	at opwvhk.intellij.avro_idl.AvroIdlFileType.<clinit>(AvroIdlFileType.java:16)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1042)
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:186)
	at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1105)
	at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1086)
	at java.base/java.lang.reflect.Field.get(Field.java:418)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.instantiateFileTypeBean(FileTypeManagerImpl.java:438)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.mergeOrInstantiateFileTypeBean(FileTypeManagerImpl.java:407)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.instantiatePendingFileTypes(FileTypeManagerImpl.java:399)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.getRegisteredFileTypes(FileTypeManagerImpl.java:755)
	at com.intellij.psi.stubs.StubUpdatingIndex.instantiateElementTypesFromFields(StubUpdatingIndex.java:429)
	at com.intellij.psi.stubs.StubUpdatingIndex.lambda$ensureSerializationManagerInitialized$0(StubUpdatingIndex.java:421)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:218)
	at com.intellij.psi.stubs.StubUpdatingIndex.ensureSerializationManagerInitialized(StubUpdatingIndex.java:420)
	at com.intellij.psi.stubs.StubUpdatingIndex.getValueExternalizer(StubUpdatingIndex.java:339)
	at com.intellij.util.indexing.impl.storage.DefaultIndexStorageLayout.createIndexStorage(DefaultIndexStorageLayout.kt:58)
	at com.intellij.util.indexing.impl.storage.DefaultIndexStorageLayout$SingleEntryStorageLayout.openIndexStorage(DefaultIndexStorageLayout.kt:149)
	at com.intellij.psi.stubs.StubUpdatingIndex$3.openIndexStorage(StubUpdatingIndex.java:380)
	at com.intellij.util.indexing.impl.storage.TransientFileContentIndex$1.openIndexStorage(TransientFileContentIndex.java:40)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.lambda$new$0(VfsAwareMapReduceIndex.java:67)
	at com.intellij.util.indexing.impl.MapReduceIndex.<init>(MapReduceIndex.java:102)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.<init>(VfsAwareMapReduceIndex.java:80)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.<init>(VfsAwareMapReduceIndex.java:66)
	at com.intellij.util.indexing.impl.storage.TransientFileContentIndex.<init>(TransientFileContentIndex.java:36)
	at com.intellij.psi.stubs.StubUpdatingIndexStorage.<init>(StubUpdatingIndexStorage.java:32)
	at com.intellij.psi.stubs.StubUpdatingIndex.createIndexImplementation(StubUpdatingIndex.java:372)
	at com.intellij.util.indexing.FileBasedIndexImpl.createIndex(FileBasedIndexImpl.java:542)
	at com.intellij.util.indexing.FileBasedIndexImpl.initIndexStorage(FileBasedIndexImpl.java:479)
	at com.intellij.util.indexing.FileBasedIndexImpl.registerIndexer(FileBasedIndexImpl.java:439)
	at com.intellij.util.indexing.FileBasedIndexDataInitialization.lambda$initAssociatedDataForExtensions$0(FileBasedIndexDataInitialization.java:79)
	... 17 more
Caused by: com.intellij.diagnostic.ImplementationConflictException: Language with ID 'AvroIDL' is already registered: class claims.bold.intellij.avro.idl.AvroIdlLanguage
	at com.intellij.lang.Language.<init>(Language.java:84)
	at com.intellij.lang.Language.<init>(Language.java:60)
	at opwvhk.intellij.avro_idl.AvroIdlLanguage.<init>(AvroIdlLanguage.java:17)
	at opwvhk.intellij.avro_idl.AvroIdlLanguage.<clinit>(AvroIdlLanguage.java:14)
	... 53 more

**Comment by opwvhk** [comment] 2021-06-14 12:26
Sorry for the late reply..

But thank you for this last stack trace. It's very revealing!

I see now, that there is a conflict with the older Avro plugin, which causes this root exception:
```
Caused by: com.intellij.diagnostic.ImplementationConflictException: Language with ID 'AvroIDL' is already registered: class claims.bold.intellij.avro.idl.AvroIdlLanguage
```

I've renamed the defined languages in the plugin, so this issue should be fixed in the next version.

As a workaround, can you please enable either this plugin, or the one from Abigail Buccaneer ("Apache Avro™ support"), but not both?

**Closed** 2021-06-22 11:50 UTC
